#! /bin/bash

mkmarkdown cande.book
mkodt cande.book
md2html cande.book
kindlegen cande.opf
ebook-convert cande.mobi cande.epub
mkmarkdown edgenet.book
mkodt edgenet.book

rm -rf output

cp cande.md   $HOME/work/cande/website
cp cande.epub $HOME/work/cande/website/download
cp edgenet.md $HOME/work/cande/website
